/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2021-01-11 05:22:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class address_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/workspace_java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dingcan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1610159261496L));
    _jspx_dependants.put("jar:file:/E:/workspace_java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dingcan/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>购物商城</title>\r\n");

		response.addHeader("Cache-Control", "no-store, must-revalidate"); 
		response.addHeader("Expires", new java.util.Date().getTime()+"");
		
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/user.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script language=\"javascript\" type=\"text/javascript\"src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script language=\"javascript\" type=\"text/javascript\"> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar code ; //在全局 定义验证码\r\n");
      out.write("function createCode(){ \r\n");
      out.write("code = \"\";\r\n");
      out.write("var codeLength = 4;//验证码的长度\r\n");
      out.write("var checkCode = document.getElementById(\"checkCode\");\r\n");
      out.write("checkCode.value = \"\";\r\n");
      out.write("\r\n");
      out.write("var selectChar = new Array(2,3,4,5,6,7,8,9,'A','B','C','D','E','F','G','H','J','K','L','M','N','P','Q','R','S','T','U','V','W','X','Y','Z');\r\n");
      out.write("\r\n");
      out.write("for(var i=0;i<codeLength;i++) {\r\n");
      out.write("   var charIndex = Math.floor(Math.random()*32);\r\n");
      out.write("   code +=selectChar[charIndex];\r\n");
      out.write("}\r\n");
      out.write("if(code.length != codeLength){\r\n");
      out.write("   createCode();\r\n");
      out.write("}\r\n");
      out.write("checkCode.value = code;\r\n");
      out.write("}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction checkregisterform(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar inputCode = document.getElementById(\"input1\").value.toUpperCase();\r\n");
      out.write("\r\n");
      out.write("if(inputCode.length <=0) {\r\n");
      out.write("   alert(\"请输入验证码！\");\r\n");
      out.write("   return false;\r\n");
      out.write("}\r\n");
      out.write("else if(inputCode != code ){\r\n");
      out.write("   alert(\"验证码输入错误！\");\r\n");
      out.write("   createCode();\r\n");
      out.write("   return false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\t \r\n");
      out.write("\t if (document.getElementById('usernameid').value==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"收货人不能为空\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t if (document.getElementById('addressid').value==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"收货地址不能为空\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t if (document.getElementById('phoneid').value==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"联系电话不能为空\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn true;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body background=\"img/bg2.jpg\"  onload=\"createCode();\">\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<div id=\"Layer1\">\r\n");
      out.write("\t\t\t\t\t<div id=\"Layer2\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\".\"><span style=\"font-size: 30px;color: #f4a431;\"><br/>美食订餐</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"Layer20\">\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<span style=\"color: #1880c0;font-weight: bold;font-size: 40px; \">填写收货信息</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"qiantaimethod!createorder\" onsubmit=\"return checkregisterform()\" method=\"post\" >\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("\t\t\t\t订餐人\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("   \t\t\t\t<td width=\"300\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("   \t\t\t\t\t<input type=\"text\" name=\"username\" size=\"30\"  id=\"usernameid\"/>\r\n");
      out.write("   \t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("\t\t\t\t收货地址\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("   \t\t\t\t<td width=\"300\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("   \t\t\t\t\t<input type=\"text\" name=\"address\" size=\"30\" id=\"addressid\"/>\r\n");
      out.write("   \t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("\t\t\t\t联系电话\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("   \t\t\t\t<td width=\"300\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("   \t\t\t\t\t<input type=\"text\" name=\"phone\" size=\"30\" id=\"phoneid\"/>\r\n");
      out.write("   \t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("\t\t\t\t验证码\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("   \t\t\t\t<td width=\"300\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("   \t\t\t\t\t<input type=\"text\" id=\"input1\" />\r\n");
      out.write("   \t\t\t\t\t<input type=\"text\" id=\"checkCode\" class=\"code\" style=\"width: 55px\" /> <a href=\"####\" onclick=\"createCode()\">看不清楚</a>\r\n");
      out.write("   \t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"250\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("\t\t\t\t操作\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("   \t\t\t\t<td width=\"300\" background=\"img/bg7.jpg\" height=\"35\">\r\n");
      out.write("   \t\t\t\t\t<input type=\"submit\" value=\"提交\" />\r\n");
      out.write("   \t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("   \t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("   \t\t\t\t\t<input type=\"reset\" value=\"重置\" />\r\n");
      out.write("   \t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
